# Generated by Django 3.2.25 on 2026-10-05 01:31

from django.db import migrations, models
import djongo.models.fields
import farmacias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('paciente', djongo.models.fields.EmbeddedField(model_container=farmacias.models.PacienteDispensacion)),
                ('medicamento', djongo.models.fields.EmbeddedField(model_container=farmacias.models.MedicamentoDispensacion)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.FloatField()),
                ('fecha_vencimiento', models.DateField()),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
