# Generated by Django 3.2.25 on 2026-10-05 01:31

from django.db import migrations, models
import djongo.models.fields
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('rol', djongo.models.fields.EmbeddedField(model_container=usuarios.models.Rol)),
            ],
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
