# Generated by Django 3.2.25 on 2026-10-05 01:31

import citas.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(max_length=300)),
                ('estado', models.CharField(max_length=20)),
                ('paciente', djongo.models.fields.EmbeddedField(model_container=citas.models.PacienteCita)),
                ('medico', djongo.models.fields.EmbeddedField(model_container=citas.models.MedicoCita)),
            ],
        ),
    ]
