# Generated by Django 3.2.25 on 2026-10-05 01:31

from django.db import migrations, models
import djongo.models.fields
import facturaciones.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('estado', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('paciente', djongo.models.fields.EmbeddedField(model_container=facturaciones.models.DatosPacienteFactura)),
                ('conceptos', djongo.models.fields.ArrayField(model_container=facturaciones.models.ConceptoFactura)),
            ],
        ),
    ]
