# Generated by Django 3.2.25 on 2026-10-05 01:31

from django.db import migrations, models
import djongo.models.fields
import historias_clinicas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', djongo.models.fields.EmbeddedField(model_container=historias_clinicas.models.PacienteHistoria)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('antecedentes', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
